services:
  postgres_db_test:
    image: postgres:17-alpine
    container_name: postgres-test
    hostname: postgres_db_test
    restart: always
    env_file:
      - ".env_test"
    volumes:
      - postgres-db-test:/var/lib/postgresql/data
    networks:
      - dbnet

  postgres_db_dev:
    image: postgres:17-alpine
    container_name: postgres_dev
    hostname: postgres_db_dev
    restart: always
    env_file:
      - ".env_dev"
    volumes:
      - postgres-db-dev:/var/lib/postgresql/data
    networks:
      - dbnet

  adminer:
    image: adminer:standalone
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - "postgres_db_test:db_test"
      - "postgres_db_dev:db"
    networks:
      - dbnet
    depends_on:
      - postgres_db_dev
      - postgres_db_test

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-db-test:
  postgres-db-dev: